# Generated by Django 2.2 on 2019-05-07 13:56

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phonenumber',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='default_user_icon.jpg', upload_to=store.models.user_directory_path),
        ),
    ]
