# Generated by Django 2.2 on 2019-05-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20190507_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
