# Generated by Django 2.2 on 2019-05-10 16:38

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20190510_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='default_user_icone.jpg', upload_to=store.models.user_directory_path),
        ),
    ]
