# Generated by Django 2.2 on 2019-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20190510_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
        ),
    ]
